/// Lifecycle states a queued network request can be in.
enum RequestStatus { queued, active, retrying, completed, failed }

extension RequestStatusX on RequestStatus {
  String get label {
    switch (this) {
      case RequestStatus.queued:
        return 'Queued';
      case RequestStatus.active:
        return 'Active';
      case RequestStatus.retrying:
        return 'Retrying';
      case RequestStatus.completed:
        return 'Completed';
      case RequestStatus.failed:
        return 'Failed';
    }
  }

  /// Terminal states are the ones the queue can safely clean up.
  bool get isTerminal => this == RequestStatus.completed || this == RequestStatus.failed;

  /// Requests that currently hold a connection.
  bool get isInFlight => this == RequestStatus.active || this == RequestStatus.retrying;
}

/// Describes the simulated payload a request downloads.
///
/// The values are encoded into the request URL so the simulated HTTP client
/// knows how much data to stream back and how slow the link should be.
class RequestProfile {
  const RequestProfile({
    required this.id,
    required this.label,
    required this.path,
    required this.totalBytes,
    required this.chunkCount,
    required this.chunkDelay,
  });

  final String id;
  final String label;
  final String path;
  final int totalBytes;
  final int chunkCount;
  final Duration chunkDelay;

  /// Roughly how long the transfer takes on a healthy link.
  Duration get estimatedDuration => chunkDelay * chunkCount;

  Uri get endpoint => Uri.https(
        'api.portfolio-demo.dev',
        path,
        <String, String>{
          'bytes': '$totalBytes',
          'chunks': '$chunkCount',
          'chunkDelayMs': '${chunkDelay.inMilliseconds}',
        },
      );

  /// Small, quick transfer used to keep the queue moving.
  static const RequestProfile standard = RequestProfile(
    id: 'standard',
    label: 'Standard API payload',
    path: '/v1/media/thumbnail',
    totalBytes: 256 * 1024,
    chunkCount: 8,
    chunkDelay: Duration(milliseconds: 120),
  );

  /// Long running transfer used to demonstrate interruption + auto recovery.
  static const RequestProfile large = RequestProfile(
    id: 'large',
    label: 'Large media payload',
    path: '/v1/media/large-payload',
    totalBytes: 5 * 1024 * 1024,
    chunkCount: 30,
    chunkDelay: Duration(milliseconds: 260),
  );
}

/// A single request tracked by the request queue.
class NetworkRequest {
  const NetworkRequest({
    required this.id,
    required this.label,
    required this.status,
    required this.createdAt,
    required this.profile,
    this.attempt = 1,
    this.progress = 0,
    this.receivedBytes = 0,
    this.message,
    this.elapsed,
    this.completedAt,
  });

  static const Object _unset = Object();

  /// Unique identifier generated by the queue controller.
  final String id;

  /// Display name, e.g. "Large media payload #2".
  final String label;

  /// Current lifecycle state.
  final RequestStatus status;

  /// When the request entered the queue.
  final DateTime createdAt;

  /// Payload description.
  final RequestProfile profile;

  /// Number of execution attempts (1 = first pass, 2+ = recovery pass).
  final int attempt;

  /// Download progress in the 0..1 range.
  final double progress;

  /// Bytes received during the current attempt.
  final int receivedBytes;

  /// Human readable note about the current state.
  final String? message;

  /// Duration of the last successful attempt.
  final Duration? elapsed;

  /// Timestamp of the successful completion.
  final DateTime? completedAt;

  int get totalBytes => profile.totalBytes;

  Uri get endpoint => profile.endpoint;

  /// Compact endpoint label rendered in the request tiles.
  String get endpointLabel => '${profile.endpoint.host}${profile.endpoint.path}';

  /// True if this request was interrupted and is waiting for connectivity.
  bool get isWaitingForNetwork => status == RequestStatus.queued;

  NetworkRequest copyWith({
    RequestStatus? status,
    int? attempt,
    double? progress,
    int? receivedBytes,
    Object? message = _unset,
    Object? elapsed = _unset,
    Object? completedAt = _unset,
  }) {
    return NetworkRequest(
      id: id,
      label: label,
      status: status ?? this.status,
      createdAt: createdAt,
      profile: profile,
      attempt: attempt ?? this.attempt,
      progress: progress ?? this.progress,
      receivedBytes: receivedBytes ?? this.receivedBytes,
      message: identical(message, _unset) ? this.message : message as String?,
      elapsed: identical(elapsed, _unset) ? this.elapsed : elapsed as Duration?,
      completedAt:
          identical(completedAt, _unset) ? this.completedAt : completedAt as DateTime?,
    );
  }

  @override
  String toString() =>
      'NetworkRequest($id, ${profile.id}, ${status.label}, attempt: $attempt, '
      'progress: ${(progress * 100).round()}%)';
}

/// Formats a byte count into a short human readable string (1.5 MB, 256 KB).
String formatBytes(int bytes) {
  if (bytes < 1024) {
    return '$bytes B';
  }
  const List<String> units = <String>['KB', 'MB', 'GB'];
  var value = bytes / 1024;
  var unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex++;
  }
  final String formatted = value >= 10 ? value.toStringAsFixed(0) : value.toStringAsFixed(1);
  return '$formatted ${units[unitIndex]}';
}

/// Formats a duration into milliseconds or seconds for compact UI chips.
String formatDurationShort(Duration duration) {
  if (duration.inMilliseconds < 1000) {
    return '${duration.inMilliseconds} ms';
  }
  return '${(duration.inMilliseconds / 1000).toStringAsFixed(1)} s';
}